services:
  db-e_comerse:
    image: postgres:17-alpine
    container_name: db-e_comerse
    environment:
      POSTGRES_DB: prueba_todo_code
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Estudent1!

    ports:
      - "5431:5432"
    volumes:
      - db-e_comerse_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d prueba_todo_code"]
      interval: 10s
      timeout: 20s
      retries: 4
      start_period: 20s

  e_comerse_app:
    container_name: e_comerse_app
    image: e-comerse_app:v1
    environment:
      DB_HOST: db-e_comerse
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Estudent1!
      DB_NAME: prueba_todo_code
    ports:
      - "9090:9090"
    depends_on:
       db-e_comerse:
         condition: service_healthy

    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 7s
        max_attempts: 5

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: estainlinv@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin




volumes:
  db-e_comerse_data:
    driver: local
  pgadmin_data:
    driver: local